### ISSUE TITLE
"long name" specified with a single "-" is recognized as "short name+argument"

### ISSUE THREAD

**Issue by schaazzz** [rust-lang/getopts#101]
**Steps to reproduce**:
- Use both long and short names (e.g. "c" & "config")
- Specify long name on the CLI with a single "-" (e.g. "-config")

**Expectation**:
- Option is not matched

**Observed**:
- getopts matches as short name with rest of the string returned as argument (e.g. with "-config" matches "c" and returns "onfig" as the argument)

**Sample code:**

`

      fn main() -> std::io::Result<()> {
         let args: Vec<String> = env::args().collect(); 
         let program = args[0].clone();
         let mut opts = Options::new();

         opts.reqopt("c", "config", "Configuration file", "FILE");
         opts.optflag("h", "help", "Print this help menu");

         let matches = match opts.parse(&args[1..]) {
             Ok(m) => {
                 println!("Match found..." );
                 println!("{:?}", m.opt_str("config"));
                 m
             }
             Err(_f) => { 
                 println!("No match found...");
              }
         };

         Ok(())
    }
`

**Comment by LukasKalbertodt** [comment]
This is intended actually. From the docs:

> Options that expect an argument accept their argument following either a space or an equals sign. Single-character options don't require the space.

It's fairly common to omit the space, in particular when the value is a number. E.g. `make -j16` or `watch -n3`. 
This can sometimes be confusing, like in your example, but that's unfortunately unavoidable if one wants to omit the space.

**Comment by schaazzz** [comment]
I get your point but from an end user perspective this is a wierd situation because the error information would be misleading. Anyway, until I can think of a better solution, I've switched to "i" and "config" as the short and long names, respectively.
