### ISSUE TITLE
Option Groups

### ISSUE THREAD

**Issue by markschl** [rust-lang/getopts#13]
Are there any plans of supporting option grouping in the style of [Python's argparse module](https://docs.python.org/3/library/argparse.html#argument-groups)? At least for me that would be on top of the whishlist because I think thematic grouping of options on the usage output can improve readability very much.
I could imagine having a similar API as the argparse one:

```
...
options.optflag("v", "version", "Print program version");
let optgroup = options.add_option_group("Output options", 
                                        "Options for defining the output file and format");
optgroup.optopt("o", "outfile", "Output file", "FILE");
optgroup.optflag("c", "compress", "Compress output with GZIP");
print!("{}", opts.usage("Usage: mytool [options] <input>"));
```

output:

```
Usage: mytool [options] <input>

Options:
    [...]
    -v --version        Print version info and exit

Output Options:
    Options for defining the output file and format

    -o --outfile FILE Output file (output defaults to stdin)
    -c --compress    Compress output with GZIP
```

There are other things that I like about argparse such as handling of positional arguments and the [possibility allow undefined arguments](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_known_args), but I don't know whether there is an intention to keep getopts as simple as possible...

**Comment by steveklabnik** [comment]
You might want to checkout docopt

**Comment by marcsch** [comment]
I tried docopt and liked it, although I still prefer the getopts/argparse approach (maybe just because I'm more used to it). In this particular case I switched back to getopts because I had difficulties implementing a subcommand pattern. getopts seemed more flexible in this case, but maybe it's because I haven't yet found the right way of doing it in docopt.

**Comment by gbersac** [comment]
I am interested in such feature too.

**Comment by KodrAus** [comment]
We've effectively stopped development of `getopts` here to avoid any potential behavior changes in `rustc`.

Users who want any more advanced option parsing are encouraged to use `clap`, `docopt` or other more featured options.
