### ISSUE TITLE
Panic if the only args are "-"

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/getopts#15]
Given this Rust program:

``` rust
extern crate getopts;

use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();
    let matches = getopts::Options::new().parse(args);
}
```

The following invocation will create a panic:

```
$ ./demonstrate_bug -
thread '<main>' panicked at 'index out of bounds: the len is 1 but the index is 1', src/main.rs:1
```

This is using version getopts 0.2.4 with rustc 1.0.0-nightly (6c065fc8c 2015-02-17).

**Comment by shepmaster** [comment]
This is unfortunate as `-` is commonly used as a "filename" that means "read from stdin", which is how I hit it.
