### ISSUE TITLE
Multiple arguments to a matching option

### ISSUE THREAD

**Issue by 0X1A** [rust-lang/getopts#19]
I am not entirely sure if I missed something in the documentation but is there anyway to catch multiple arguments for a matching option? For example in `prog -n file1.txt file2.txt`, only `file1.txt` will be put into a vector for `opt_strs` in the matching option `-n` and `file2.txt` will be in `free`. Is it possible to catch all arguments following an option with getopts?

**Comment by 0X1A** [comment]
It was pointed out to me that `free` should be used or thought of as output for the argument that is returned form `opt_strs`

**Comment by Minoru** [comment]
@0X1A I understand it's been four years, but can you perhaps expand a bit on that? `free` doesn't store position indexes, so it's not clear to me how to distinguish `command a.txt -i b.txt` and `command -i a.txt b.txt`. Also not clear how to figure out which arguments belong to which of the two options, e.g. `command -i a.txt b.txt -o x.jpg y.jpg z.jpg` will parse into:
- `-i a.txt`;
- `-o x.jpg`;
- `free` = `b.txt y.jpg z.jpg`, from which it's impossible to figure out what the first one belongs to `-i` and the other two to `-o`.

**Comment by 0X1A** [comment]
@Minoru Hi, as you mentioned it's been quite a while since I initially opened this issue and I mostly use clap-rs now. That being said I seem to recall that getopts essentially forces you to have a set list of 'output' parameters for what ever options you pass it. So using your example, composing options such that `command -i a.txt b.txt -o x.jpg y.jpg z.jpg` would work as you would intuit is not possible. Instead, getopts sees this as `command -i a.txt -o x.jpg y.jpg z.jpg b.txt`. I could easily be wrong, as I haven't used getopts in quite a long while. Sorry if I can't be of more help! You could always try the [Rust discord](https://discord.gg/6e8Webb)
