### ISSUE TITLE
[Question/Feature Request]

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [rust-lang/getopts#93]
### [Question/Feature Request]
Can you take parameters that aren't flags? apt for example does...
```sh
apt install
apt upgrade
```
If so how does one implement that?

### Question 2
How does one implement their own fail for each argument? Instead of seeing
```sh
Argument to option 'S' missing
```
I'd like
```sh
error: no targets specified (use -h for help)
```
and have multiple different options for different arguments.

**Comment by ExpHP** [comment]
1. You can use the [`StopAtFirstFree` parsing style](https://docs.rs/getopts/0.2.21/getopts/struct.Options.html#method.parsing_style) to stop at the `install` or `upgrade` token, placing them and everything afterwards in `free`.
