### ISSUE TITLE
Positional Arguments

### ISSUE THREAD

**Issue by alexxbb** [rust-lang/getopts#98]
I can't seem to find a way to add a positional argument. i.e I don't want to pass a flag.

```my_cmd foo``` instead of ```my_cmd -v value```

Is it possible?

**Comment by alexxbb** [comment]
I found a Vec of Strings in ```args.free``` so I can work up from there. Is there a way to require this positional, so that ```opts.parse()``` would check it's presence?

**Comment by tromey** [comment]
> I found a Vec of Strings in `args.free` so I can work up from there. Is there a way to require this positional, so that `opts.parse()` would check it's presence?

You have to do that part by hand, after parsing the arguments.  The docs have an example that does this: https://docs.rs/getopts/0.2.21/getopts/#example
